/**
 * Write `deno.local.jsonc` from whatever is actually on disk right now.
 *
 * The drivers are unpublished and live on `hardware-libs` branches that have not merged, so running
 * the backend means resolving them from a local checkout. Which packages exist there depends on the
 * branch that checkout happens to be on: `omron/` is only on `feat/omron-v4ku`, `desko/` only on
 * `feat/desko-penta`, and `serial/` was deleted by the USB-serial rewrite. Hand-maintaining a map
 * across those switches is how you end up pointing a specifier at a package the branch does not
 * have and reading the TS2307 as a driver bug.
 *
 * So this asks the filesystem instead of being told: for each specifier, take the first root that
 * has the file. Switch the checkout to another branch, run this again, and the map follows.
 *
 * The result is gitignored, and `deno.jsonc` is never touched — committing local paths is the
 * mistake facepod-tester made, where a clone without `hardware-libs` beside it failed to build.
 *
 * @module
 */

import { dirname, fromFileUrl, join, relative, resolve } from "@std/path";

/** Where a driver package might be checked out, nearest first. */
const ROOTS = ["../hardware-libs", "../wt-desko-penta", "../wt-ier-driver", "../wt-pr55"];

/** Specifier → the file that proves the package is present on this branch. */
const LOCAL: Record<string, string> = {
  "@eai/ier/s33380": "ier/s33380/mod.ts",
  "@eai/omron/v4ku": "omron/v4ku/mod.ts",
  "@eai/desko/penta": "desko/penta/mod.ts",
  "@eai/usb": "usb/mod.ts",
  // Deliberately no `@eai/hid`. The name now belongs to the HID Global FacePod package; the HID
  // report transport the card reader uses was folded into `@eai/usb`. Mapping it would resolve a
  // stale import to the wrong package and report the mismatch as a missing export.
  "@eai/serial": "serial/mod.ts",
  "@eai/shared": "shared/mod.ts",
  "@eai/hotplug": "hotplug/mod.ts",
};

/**
 * Pins that are not resolved locally, carried verbatim.
 *
 * `-c` replaces `deno.jsonc` rather than merging with it, so the generated map has to be whole.
 */
const PUBLISHED: Record<string, string> = {
  "@eai/models": "jsr:@eai/models@^1.3.0",
  "@eai/logging-ts": "jsr:@eai/logging-ts@^2.6.0",
  "@eai/async": "jsr:@eai/async@^1.0.0",
  "@std/async": "jsr:@std/async@^1.0.0",
  "@std/path": "jsr:@std/path@^1.0.0",
  "@std/bytes": "jsr:@std/bytes@^1",
  "@std/encoding": "jsr:@std/encoding@^1",
  "@std/http/file-server": "jsr:@std/http@^1/file-server",
  "@std/log": "jsr:@std/log@^0.224.0",
  "@std/assert": "jsr:@std/assert@^1.0.14",
};

/** Which device each specifier is for, so the report is about hardware rather than about packages. */
const DEVICE_OF: Record<string, string> = {
  "@eai/ier/s33380": "Light Board",
  "@eai/omron/v4ku": "Card Reader",
  "@eai/desko/penta": "Passport Reader",
};

const here = dirname(fromFileUrl(import.meta.url));
const repo = resolve(here, "..");

const exists = async (path: string) => await Deno.stat(path).then(() => true).catch(() => false);

/** The first root holding this package, or null when no checkout on disk has it. */
async function locate(marker: string): Promise<string | null> {
  for (const root of ROOTS) {
    const path = join(repo, root, marker);
    if (await exists(path)) return path;
  }
  return null;
}

const imports: Record<string, string> = {};
const found: string[] = [];
const missing: string[] = [];

for (const [specifier, marker] of Object.entries(LOCAL)) {
  const path = await locate(marker);
  if (path === null) {
    missing.push(specifier);
    continue;
  }
  /*
   * Relative to the repo, so the file reads the same on any machine. `relative()` rather than
   * slicing off a prefix: every root is a sibling, so the resolved path is *outside* this repo and
   * never carries it as a prefix — slicing silently produced "./s33380/mod.ts" from a real path.
   */
  const rel = relative(repo, path).replaceAll("\\", "/");
  imports[specifier] = rel.startsWith(".") ? rel : "./" + rel;
  found.push(specifier);
}

Object.assign(imports, PUBLISHED);

const out = join(repo, "deno.local.jsonc");
await Deno.writeTextFile(
  out,
  `// GENERATED by scripts/localmap.ts — do not edit, and do not commit.\n` +
    `// Regenerate after switching the hardware-libs checkout to another branch.\n` +
    JSON.stringify({ imports }, null, 2) + "\n",
);

console.log(`wrote deno.local.jsonc — ${found.length} local, ${missing.length} not on this branch\n`);
for (const specifier of found) console.log(`  found    ${specifier}  ->  ${imports[specifier]}`);
for (const specifier of missing) {
  const device = DEVICE_OF[specifier];
  console.log(`  absent   ${specifier}${device ? `  (${device} cannot be driven from this checkout)` : ""}`);
}
